### ISSUE TITLE
Cannot find module 'models' - Should be relative path `../models`

### ISSUE THREAD

**Issue by rado0x54** [transmute-industries/sidetree.js#122]
Hey,

I imported `"@sidetree/core": "^0.1.1-unstable.19",` into a playground project and have problems building / running with the following: The error seems correct, since it apparently should reference a relative folder.

Changing `'models'` to `'../models'` in both occurrences fixes the issue.

`node_modules/@sidetree/common/dist/interfaces/IBlockchain.d.ts(1,37): error TS2307: Cannot find module 'models' or its corresponding type declarations.`
`node_modules/@sidetree/common/dist/interfaces/ICas.d.ts(2,37): error TS2307: Cannot find module 'models' or its corresponding type declarations.`

I would do a PR, but forking and PRing from a remote seems a little overkill for two lines :)

**Comment by OR13** [comment]
@rado0x54 thanks for raising this.

**Comment by OR13** [comment]
@rado0x54 lmk if the deployment resolves it

**Comment by rado0x54** [comment]
Yes @OR13, that resolves it. Thanks for the quick turnaround.
