### ISSUE TITLE
Should @transmute/universal-wallet be a peer dependency?

### ISSUE THREAD

**Issue by NickDarvey** [transmute-industries/sidetree.js#127]
Hullo — this might be my misunderstanding of the way you're supposed to extend things using `factory.ts` and the plugin pattern used in a bunch of these wallet repos, buuut...

## Use cases
I want to define my own composition root for my wallet [like this one](https://github.com/w3c-ccg/universal-wallet-interop-spec/blob/master/packages/universal-wallet-react/src/__fixtures__/testWalletFactory.ts) so that I can add more plugins.

~~I want to expose my own [`Wallet`](https://github.com/w3c-ccg/universal-wallet-interop-spec/blob/d1c044923a9fd51c108776c58d1fd31c39b6e1fa/packages/universal-wallet/src/walletFactory.ts#L13-L25)-based interface to other parts of my app, not [`SidetreeWallet`](https://github.com/transmute-industries/sidetree.js/blob/4d952c9cda501295da5cb0765c3ed8ba65e770e7/packages/wallet/src/types/SidetreePlugin.ts#L53), so I can isolate the rest of my app from changes occurring to this Sidetree's wallet interface.~~
I no longer think this one is valid because I wasn't thinking in TypeScript. I can just define my own interface which happens to match.

## Issue
`@transmute/universal-wallet` is added as a [`dependency`](https://github.com/transmute-industries/sidetree.js/blob/4d952c9cda501295da5cb0765c3ed8ba65e770e7/packages/wallet/package.json#L35).

## Fix
Add it as a `peerDependency`.

## Workaround
Install a matching version of `@transmute/universal-wallet` into my app.

**Comment by OR13** [comment]
@NickDarvey thanks for reporting this. I think you are right.

The idea with the plugins is that you can compose them, in the case of sidetree, the sidetree wallet should be just another universal wallet plugin.
