### ISSUE TITLE
Add a version of CI that does not require secrets

### ISSUE THREAD

**Issue by gjgd** [transmute-industries/sidetree.js#129]
External contributors can submit PRs, but CI doesn't run on their code because the CI action uses secrets.

Separate ci.yml into two actions:
- ci-public.yml: run tests that don't require secrets (all but the photon ones)
- ci-private.yml: run tests that require secrets (the photon ones)

**Comment by BenjaminMoe** [comment]
I think this has been addressed. For AWS we added a Mock-QLDB and a Mock-S3 interface that is enabled by default unless specifically enabled, so that tests can run against the mock AWS interfaces.
