### ISSUE TITLE
Support for other crypto algos?

### ISSUE THREAD

**Issue by NickDarvey** [transmute-industries/sidetree.js#130]
⚠ Heads-up: misconceptions likely follow

I want to use a [Web Crypto-compatible](https://diafygi.github.io/webcrypto-examples/) algorithm for signing and key agreement (and encryption) so that I could [`importKey`](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-importKey) and rely on the platform to store keys safely. 

Should I just grab a library like [`@transmute/did-key-web-crypto`](https://github.com/transmute-industries/did-key.js/tree/master/packages/did-key-web-crypto) and follow along with how it's done in [`toDidDocForProfile`](https://github.com/transmute-industries/sidetree.js/blob/d1e429620d73ed563f40e909882069c0f3150df8/packages/wallet/src/functions/toDidDocForProfile.ts#L24-L98), or is there another way I should be extending `@sidetree/wallet`'s existing interfaces, or should I be contributing support for new options to `@sidetree/wallet` itself?

(If it's either of the latter I might need some pointers on seeding with `secureRandom`, though that question might be better asked on [`did-key.js`](https://github.com/transmute-industries/did-key.js).)

**Comment by OR13** [comment]
under the new v1 interfaces, the IonKey module needs to support the signers, today, it only supports secp256k1, see https://github.com/transmute-industries/sidetree.js/issues/276

We would need to update it to support all the other variants of did-key we support eventually.

The interfaces referenced here has drifted, feel free to open a new issue for the new ones.
