### ISSUE TITLE
Sidetree.js not working in docker container

### ISSUE THREAD

**Issue by kc1116** [transmute-industries/sidetree.js#154]
When trying to build a nodejs express app that uses sidetree.js in a docker container I keep getting errors involving the import of ./versions/'latest'/MongoDbOperationQueue. Below is the error I am receiving, this is a brand new error btw. Also everything works fine locally, this issue is only present in docker. 

{
	"level": 50,
	"stack": "Error: could not initialize Sidetree Element: Error: Cannot find module './versions/'latest'/MongoDbOperationQueue'\nRequire stack:\n- /usr/src/app/node_modules/@sidetree/core/dist/core.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/core/dist/index.js\n- /usr/src/app/node_modules/@sidetree/did-method/dist/did-method.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/did-method/dist/index.js\n- /usr/src/app/node_modules/@sidetree/element/dist/element.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/element/dist/index.js\n- /usr/src/app/src/sidetree/element/element.ts\n- /usr/src/app/src/sidetree/element/index.ts\n- /usr/src/app/src/did/did.controller.ts\n- /usr/src/app/src/routes/routes.ts\n- /usr/src/app/src/app.ts\n- /usr/src/app/src/index.ts\n    at /usr/src/app/src/sidetree/element/element.ts:48:13\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/sidetree/element/element.ts:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
	"type": "Error",
	"msg": "could not initialize Sidetree Element: Error: Cannot find module './versions/'latest'/MongoDbOperationQueue'\nRequire stack:\n- /usr/src/app/node_modules/@sidetree/core/dist/core.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/core/dist/index.js\n- /usr/src/app/node_modules/@sidetree/did-method/dist/did-method.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/did-method/dist/index.js\n- /usr/src/app/node_modules/@sidetree/element/dist/element.cjs.development.js\n- /usr/src/app/node_modules/@sidetree/element/dist/index.js\n- /usr/src/app/src/sidetree/element/element.ts\n- /usr/src/app/src/sidetree/element/index.ts\n- /usr/src/app/src/did/did.controller.ts\n- /usr/src/app/src/routes/routes.ts\n- /usr/src/app/src/app.ts\n- /usr/src/app/src/index.ts"
}

**Comment by gjgd** [comment]
Thanks for reporting! Not sure why this is happening, we use sidetree.js running in a docker container for internal use and it works. Can you share code that reproduces the error?

**Comment by kc1116** [comment]
Yes below is the code thats initializing sidetree in an express app to create a sidetree node. I following following the examples pointed out by @OR13 to the tee. 

```
/* eslint-disable id-match */
import Web3 from 'web3'
import { EthereumLedger } from '@sidetree/ethereum'
import { IpfsCasWithCache } from '@sidetree/cas-ipfs'
import { Element } from '@sidetree/element'

export interface ElementConfig {
  applicationWalletPrivateKey: string
  contentAddressableStoreServiceUri: string
  databaseName: string
  didMethodName: string
  ethereumRpcUrl: string
  mongoDbConnectionString: string
  batchingIntervalInSeconds: number
  observingIntervalInSeconds: number
  maxConcurrentDownloads: number
  elementAnchorContract: string
  versions: any
}

export class DidElement {
  static getLedger = async (config: ElementConfig): Promise<EthereumLedger> => {
    const web3 = new Web3(config.ethereumRpcUrl)
    const { applicationWalletPrivateKey } = config
    const acct = web3.eth.accounts.privateKeyToAccount(applicationWalletPrivateKey)
    web3.eth.accounts.wallet.add(acct)
    const a = web3.eth.accounts.create()
    return new EthereumLedger(web3, config.elementAnchorContract)
  }

  static getCas = async (config: ElementConfig): Promise<IpfsCasWithCache> => {
    return new IpfsCasWithCache(
      config.contentAddressableStoreServiceUri,
      config.mongoDbConnectionString,
      config.databaseName
    )
  }

  static initialize = async (config: ElementConfig, startObserver = false, startBatchWriter = false): Promise<Element> => {
    try {
      const cas = await DidElement.getCas(config)
      const ledger = await DidElement.getLedger(config)

      const element = new Element(config, config.versions, ledger, cas)
      await element.initialize(startObserver, startBatchWriter)
      return element
    } catch (error) {
      throw new Error(`could not initialize Sidetree Element: ${error}`)
    }
  }
}
```

And here is my docker file. 

```
FROM node:14.16.0-alpine3.10

ARG NODE_AUTH_TOKEN
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json package-lock.json /usr/src/app/

RUN touch ~/.npmrc && printf "@org:my-org=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN\nunsafe-perm=true" > ~/.npmrc
RUN npm ci

COPY . /usr/src/app

RUN npm run build

ENV NODE_ENV production

EXPOSE 3000

CMD [ "npm", "start" ]

```

Can you please commit the working Dockerfile? I believe these issues pertain to Node more than Sidetreejs it'self. This problem happened randomly, a day ago everything was working perfectly fine and we were serving Sidetree requests with no problem with our service deployed and running in k8s.

**Comment by gjgd** [comment]
Looking at the error, I suspect the `versions` array in the config may be wrong?

Here is a working example of the code you provided to successfully initialized Element inside a docker container without error: https://github.com/gjgd/demo-element-in-docker

**Comment by BenjaminMoe** [comment]
We've added a little more documentation that covers running element in docker. 
https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/docker/element/dev

For now I'm going to go ahead and close this. We can re-open this issue with respect to the current changes since this ticket seems kind of stale.
