### ISSUE TITLE
operationDdata byte size of 1367 exceeded limit of 1000

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#166]
In the didDocument, I've added some service_endpoints and the createOperation  delta payload too big e.g around 1367 bytes and I encountered the following error 
operationDdata byte size of 1367 exceeded limit of 1000

How to change the limit of protocolParameters.maxDeltaSizeInBytes?

**Comment by thomas-tran** [comment]
@OR13 , @gjgd  Do you know how to make change on this?

**Comment by OR13** [comment]
I think this is the point you are hitting:

https://github.com/transmute-industries/sidetree.js/blob/1350d9122abb3f3d1cc26656ec6059cce2ac143c/packages/core/src/write/ChunkFile.ts#L90

https://github.com/transmute-industries/sidetree.js/blob/1350d9122abb3f3d1cc26656ec6059cce2ac143c/packages/common/src/util/parameters.ts#L29

I've not tried to change them recently,  Looks like ION just uses the default: https://github.com/decentralized-identity/ion/search?q=maxDeltaSizeInBytes

**Comment by BenjaminMoe** [comment]
I think the max size in bytes applies to the gzipped size of the operation. This is another thing that I need to look for while comparing to Ion.

**Comment by OR13** [comment]
yep, we pretty much don't want to change this parameter to be larger than whatever ION mainnet supports. @BenjaminMoe  to confirm their config value.
