### ISSUE TITLE
handleOperationRequest did not return the didDocument

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#168]
I ran this code to generate the createOperationRequest

const  mnemonic = 'such emerge bargain left need together glory oval add unusual pear abstract';
const createOperation = await getCreateOperationForProfile(
  mnemonic,
  0,
  profile
);

const createPatch = {
  service_endpoints: [
    {
      id: 'linkedregistry-0',
      type: 'LinkedRegistry',
      endpoint:
        'https://gateway.linkedregistry.io/account/230D811F8D5CCA2C982641697C57A0D7FCF09665394BC87F9CC06CD3747E25F3',
    },
  ],
};
const createOperationWithPatch = await getCreateOperationForProfile(
  mnemonic,
  0,
  profile,
  createPatch
);

Result 

{
        "type": "create",
        "suffix_data": "eyJkZWx0YV9oYXNoIjoiRWlCdWg4T1ZfQmxsZ0U1MFdCM2tkMGFMTnVtN3BqRnpsbkx1MnRhakIxWV9GdyIsInJlY292ZXJ5X2NvbW1pdG1lbnQiOiJFaUQ3LWM5dXhxZi1oLVpORGlrNmNTM1FJU2N3S1VZRmJTNUlhYWxRTl93Z3Z3In0",
        "delta": "eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljX2tleXMiOlt7ImlkIjoiejZNa2tIcW95emsxOFpqOWhxSHFBUTVWRDZzaG9EOGFFemRXNTZHNDdhRWdkZjE0IiwiandrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiVnJ4OS1zeGE1V0x3ZjV1eHF5cnBqakZSY29vS2NTUllQbkY2NDBMeEVjcyJ9LCJwdXJwb3NlIjpbImdlbmVyYWwiLCJhdXRoIiwiYXNzZXJ0aW9uIiwiaW52b2NhdGlvbiIsImRlbGVnYXRpb24iXSwidHlwZSI6Ikpzb25XZWJLZXkyMDIwIn0seyJpZCI6Ino2TFNlYnd4M1Rjb2VLQjd2ZDFmbmU0ckVZalBjczJlWG9neGVMc3l5OWhXRkdVbSIsImp3ayI6eyJjcnYiOiJYMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiSzMzTGkza3FldGtXandFV0JaWXpWUURSdEk3M1FHU2FNRUN5Rkg2RFEyWSJ9LCJwdXJwb3NlIjpbImdlbmVyYWwiLCJhZ3JlZW1lbnQiXSwidHlwZSI6Ikpzb25XZWJLZXkyMDIwIn1dLCJzZXJ2aWNlX2VuZHBvaW50cyI6W3siZW5kcG9pbnQiOiJodHRwczovL2dhdGV3YXkubGlua2VkcmVnaXN0cnkuaW8vYWNjb3VudC8yMzBEODExRjhENUNDQTJDOTgyNjQxNjk3QzU3QTBEN0ZDRjA5NjY1Mzk0QkM4N0Y5Q0MwNkNEMzc0N0UyNUYzIiwiaWQiOiJsaW5rZWRyZWdpc3RyeS0wIiwidHlwZSI6IkxpbmtlZFJlZ2lzdHJ5In1dfX1dLCJ1cGRhdGVfY29tbWl0bWVudCI6IkVpRDctYzl1eHFmLWgtWk5EaWs2Y1MzUUlTY3dLVVlGYlM1SWFhbFFOX3dndncifQ"
      }

 const response = await element.handleOperationRequest(
    Buffer.from(
      JSON.stringify(createOperationWithPatch)
    )
  );

The response.body did not return the response.body.diddocument

{"body":{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:elem:EiB43KCpfBWZIjFWDhoXqW5iEFm1VrfQ44G7Whc3SBFalA","@context":["https://www.w3.org/ns/did/v1","https://ns.did.ai/transmute/v1",{"@base":"did:elem:EiB43KCpfBWZIjFWDhoXqW5iEFm1VrfQ44G7Whc3SBFalA"}]},"didDocumentMetadata":{"recoveryCommitment":"EiD7-c9uxqf-h-ZNDik6cS3QIScwKUYFbS5IaalQN_wgvw"}}

**Comment by OR13** [comment]
yes, the limit is enforced based on the upstream defaults.

**Comment by BenjaminMoe** [comment]
This looks resolved?
