### ISSUE TITLE
Upgrade to support Sidetree 1.0

### ISSUE THREAD

**Issue by OR13** [transmute-industries/sidetree.js#194]
This issue is to track a plan of attack for upgrading to sidetree 1.0.

The major feature delta is support for [SIP-1 Data Model Changes](https://github.com/decentralized-identity/sidetree/issues/766), but we should probably assume there are other undocumented delta's and build tests vectors from ION as the starting point.

- [x] Extract CRUD Operation test vectors from ION (including mnemonic and multiple operations)
- [x] Extract File System test vector from ION (including IPFS hashes / zlib / etc...)
- [x] Implement integration test for extracted test vectors which will fail at first.
- [x] Update sidetree.js internals to make test vector assertions pass.

**Comment by gjgd** [comment]
A non exhaustive list of action items to assess discrepancies between this implementation and the v1.0 spec

- Extract parameters from the common package. Instead they should be passed as argument in the did method config.
  - [Where some parameters currently are](https://github.com/transmute-industries/sidetree.js/blob/main/packages/common/src/util/parameters.ts)
  - [Where they should be](https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method/src/DidMethod.ts#L56)
- Make sure all parameters are up to date with this list: https://identity.foundation/sidetree/spec/v1.0.0/#default-parameters
- Make sure that the hash + encoding algorithm is still the same as the [DIF's implementation](https://github.com/decentralized-identity/sidetree/). [See](https://identity.foundation/sidetree/spec/v1.0.0/#hashing-process). 
- Make sure that the same CREATE payload will result in the same DID unique suffix as with the DIF's implementation. Use test vectors to prove it [See](https://identity.foundation/sidetree/spec/v1.0.0/#did-uri-composition)
- Make sure the public key commitment scheme aligns with the DIF's implementation. [See](https://github.com/decentralized-identity/sidetree/)
- Make sure CAS file structure is updated to reflect https://identity.foundation/sidetree/spec/v1.0.0/#file-structures **this will probably the biggest change and involve significant refactoring**
- Make sure CRUD operation syntax still match https://identity.foundation/sidetree/spec/v1.0.0/#did-operations. See also https://identity.foundation/sidetree/spec/v1.0.0/#ietf-json-patch
- Consider implementing these features for spam prevention:
  - https://identity.foundation/sidetree/spec/v1.0.0/#proof-of-fee
  - https://identity.foundation/sidetree/spec/v1.0.0/#value-locking
- Update resolver to match the new data model for output: https://identity.foundation/sidetree/spec/v1.0.0/#did-resolver-output
- Remove references to deprecated `usage` property: https://identity.foundation/sidetree/spec/v1.0.0/#usage

**Comment by JaceHensley** [comment]
I'm looking into the first item "Extract parameters from ...". There's a few places where the params are used in static method, should the values needed in those methods be passed as parameters to the static methods?

**Comment by OR13** [comment]
@JaceHensley I think we probably want to avoid changing any static method code when possible, but I know there are some cases where configuration can be provided by JSON instead oof by typescript. We tend to prefer configuration files.

**Comment by JaceHensley** [comment]
Hmm maybe I'm misunderstanding but this:

> - Extract parameters from the common package. Instead they should be passed as argument in the did method config.
>   - [Where some parameters currently are](https://github.com/transmute-industries/sidetree.js/blob/main/packages/common/src/util/parameters.ts)
>   - [Where they should be](https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method/src/DidMethod.ts#L56)

made be think that the point was to move the protocol params from being set/non-configurable to be configurable when constructing `DidMethod`. 

But then there are static methods like [this](https://github.com/transmute-industries/sidetree.js/blob/main/packages/common/src/util/AnchoredDataSerializer.ts#L62) that use the protocolParams, so I was thinking instead it would just be passed as a parameter:

```ts
public static deserialize(serializedData: string, maxOperationsPerBatch: number): AnchoredData {
  const splitData = serializedData.split(AnchoredDataSerializer.delimiter);

  if (splitData.length !== 2) {
    throw new SidetreeError(
      ErrorCode.AnchoredDataIncorrectFormat,
      `Input is not in correct format: ${serializedData}`
    );
  }

  const numberOfOperations = AnchoredDataSerializer.parsePositiveInteger(
    splitData[0]
  );

  if (numberOfOperations > maxOperationsPerBatch) {
    throw new SidetreeError(
      ErrorCode.AnchoredDataNumberOfOperationsGreaterThanMax,
      `Number of operations ${numberOfOperations} must be less than or equal to ${maxOperationsPerBatch}`
    );
  }

  return {
    anchorFileHash: splitData[1],
    numberOfOperations: numberOfOperations,
  };
}
```

**Comment by OR13** [comment]
yes, in general, we try to be a bit more functional in our implementation, but its hard because we would like to share code with the DIF one.

**Comment by OR13** [comment]
thank you @BenjaminMoe !
