### ISSUE TITLE
Update universal resolver driver for element

### ISSUE THREAD

**Issue by OR13** [transmute-industries/sidetree.js#210]
The current version is very outdated:

https://github.com/decentralized-identity/universal-resolver/blob/b0b4ea7054b971840c147edb1a1fd8d425932b54/config.json#L80

instead of:

```
"url": "https://element-did.com/api/v1/sidetree/$1",
```

it should be:

```
"url": "https://staging.element.transmute.industries/api/element/$1",
```

for example:

https://staging.element.transmute.industries/element/did:elem:ropsten:EiB840YJmTWfbUBsFx_C3TbcdAp_KkM1qTCkR3bSQIMd9Q

**Comment by BenjaminMoe** [comment]
Or maybe update it to be ropsten specific?

```
		{
			"pattern": "^did:elem:ropsten:(.+)$",
			"url": "https://ropsten.element.transmute.industries/api/1.0/identifiers/$1",
			"testIdentifiers": [ "did:elem:ropsten:EiCtwD11AV9e1oISQRHnMJsBC3OBdYDmx8xeKeASrKaw6A" ]
		},
```

**Comment by OR13** [comment]
Yeah, we want to do this ASAP....

**Comment by OR13** [comment]
https://github.com/decentralized-identity/universal-resolver/blob/dd761fe50ddb683595a940d7cfb16081bee561e0/config.json#L77

**Comment by BenjaminMoe** [comment]
https://github.com/decentralized-identity/universal-resolver/pull/287

I think we can mark this as closed.
