### ISSUE TITLE
How I could build a unanchored did:elem long form or did with initial state

### ISSUE THREAD

**Issue by Volland** [transmute-industries/sidetree.js#211]
I do not see in a library a class or helper that build an unanchored long-form or did with the initial state. 
is it a way to do it ourselves ?

**Comment by BenjaminMoe** [comment]
You're going to want to check out. https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method/src/__tests__/wallet.sanity.test.ts#L24

```
    const { mnemonic, op0 } = vectors.wallet.operations[0];
    const { delta } = op0;

    const key1 = await wallet.toKeyPair(mnemonic, 1, keyType);
    const key2 = await wallet.toKeyPair(mnemonic, 2, keyType);
    const longFormDid = await wallet.createLongFormDid({
      method: methodName,
      network: methodNetwork,
      document: delta.patches[0].document as any,
      updateKey: key2.publicKeyJwk,
      recoveryKey: key1.publicKeyJwk,
    });
```

Other related links. 

https://github.com/transmute-industries/sidetree.js/blob/main/packages/wallet/src/operations/createLongFormDid.ts
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method/src/__tests__/wallet.sanity.test.ts#L24
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/src/__test__/wallet/wallet.spec.ts#L59
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/src/__tests__/long-form-from-create-operation.test.js#L22

This is probably an older issue, but wanted to address it before marking it as resolved.
