### ISSUE TITLE
How to update the did document

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#213]
@OR13 In the wallet , I only found the method to create the createOperation request and recoveryOperation but unable to find the update and deactivate the operation request. Could anyone point out where could I find it? For example, after the creation of the did element, I'd to add the service to let other users know the point of contact using DidComm protocol

Thanks

**Comment by OR13** [comment]
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/src/__test__/sidetree-core-generated-ed25519-conformance.test.ts

But beware, we are updating the code base to Sidetree v1.0, and DIF has made a number of breaking changes between v0.1 and 1.0.

**Comment by thomas-tran** [comment]
@OR13 Do you have the time when the update is completed?

**Comment by OR13** [comment]
@thomas-tran I don't, hoping it won't take more than a few weeks, but there have been a lot of changes between v0.1 and v1... and a lot of them are specific to ION / Bitcoin related "time locking"... so hoping I can cut those out without breaking everything.

**Comment by BenjaminMoe** [comment]
For updating a did, we have examples in the `did-method` package that provides code for how to do the different operations: https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method/src/__tests__/wallet.sanity.test.ts

We also have the Ion install guide which provides a few specific curl examples to check against. 
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md#section-03-sending-a-create-operation-and-recover-operation

Hopefully this helps. Closing this issues, but comment or re-open if you have more input.
