### ISSUE TITLE
WARNING: The MNEMONIC variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by devrajsinghrawat** [transmute-industries/sidetree.js#217]
When I am starting the docker-compose then the mnemonic does not picked from .env file as mentioned in comment in docker compose file.

      # This env variable comes from the .env file in the directory in which the
      # docker-compose command is run. Here it will be ./packages/sidetree-ledger-ethereum

<img width="682" alt="Screenshot 2021-08-10 at 13 30 18" src="https://user-images.githubusercontent.com/44597990/128859504-e448dcec-2e30-40b7-8649-d9f892012a81.png">

and due to that every time, when the container is being restarted a new set of keys are being assigned. 

I am starting the container, just by right click on the docker-compose in vscode by selecting "Compose up" option.

**Comment by OR13** [comment]
hmm, seems like we probably need to separate the docker compose files so that running a local node is easier.

**Comment by devrajsinghrawat** [comment]
I ll let it open so that you can close it, when it done in future releases

**Comment by BenjaminMoe** [comment]
I think I've seen this when starting up a server. Want to see if it's happening, and why it's happening, because the seed should be defined in the configuration file.

**Comment by BenjaminMoe** [comment]
Taking some notes, it looks like this error can be reproduced by running the test for the `cas-ipfs` module. 

```
> @sidetree/cas-ipfs@0.3.1-unstable.25 pretest ~/Github/sidetree.js/packages/cas-ipfs
> docker-compose up -d ipfs mongo

WARNING: The MNEMONIC variable is not set. Defaulting to a blank string.
sidetreejs_ipfs_1 is up-to-date
sidetreejs_mongo_1 is up-to-date

> @sidetree/cas-ipfs@0.3.1-unstable.25 test ~/Github/sidetree.js/packages/cas-ipfs
> tsdx test --passWithNoTests
```

So we need to track down where that warning is coming from, and if it's needed or not.

**Comment by OR13** [comment]
This should be defaulted to an example.
