### ISSUE TITLE
PollingBlockTracker - encountered an error while attempting to update latest block

### ISSUE THREAD

**Issue by Volland** [transmute-industries/sidetree.js#218]
I am using a hdwallet-provider together with an element 

`
    const provider = new HDWalletProvider({
      mnemonic: {
        phrase: config.applicationWalletMnemonics
      },
      providerOrUrl: config.ethereumRpcUrl
    });
    const web3 = new Web3(provider)
    return new EthereumLedger(web3, config.elementAnchorContract)
`

In long run, I get an error that crashes the entire service
Error 
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:421:28)
    at Clie...
  File "/usr/src/app/node_modules/request/request.js", line 816, col 19, in ClientRequest.<anonymous>
    var e = new Error('ESOCKETTIMEDOUT')
  File "events.js", line 421, col 28, in Object.onceWrapper

version of libraries 
    "@sidetree/cas-ipfs": "0.2.6-unstable.1",
    "@sidetree/did-method": "0.2.6-unstable.1",
    "@sidetree/element": "0.2.6-unstable.1",
    "@sidetree/ethereum": "0.2.6-unstable.1",
    "@sidetree/wallet": "0.2.6-unstable.1",
   "@truffle/hdwallet-provider": "1.4.2",

**Comment by BenjaminMoe** [comment]
We updated a lot of these with the v1 updates. Now we have specific instructions for how to run a `Ganache` Element Node locally, and running a `Ropsten` testnet Element Node using Infura as a blockchain service provider. 

https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/local-dev.md

https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/local-element-ropsten-install.md

We also update the web-facing testnet Element server, which can be found here: https://ropsten.element.transmute.industries/.

Closing this issue do to lack of activity. If you have any more questions. We can follow up.
