### ISSUE TITLE
Where can I find the documentation for running a sidetree node

### ISSUE THREAD

**Issue by Muhammad-Altabba** [transmute-industries/sidetree.js#232]
Hello,
Where can I find the documentation for running an Element Sidetree node and usage examples of its REST api (create, resolve...)?
Thanks in advance,

**Comment by BenjaminMoe** [comment]
We've added a bunch of documentation files for how to run sidetree.

Running Element locally with Ganache (includes curl commands):
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/local-dev.md

Running Element testnet with Ropsten:
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/local-element-ropsten-install.md

Running Element docker with Ganache:
https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/docker/element/dev

Running Element docker with Ropsten:
https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/docker/element/test

You can see the Element API spec here:
https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/docker/element/test

We also have how to run an Ion node with curl examples for the different api at the bottom.
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md

**Comment by BenjaminMoe** [comment]
I'm going to close this issue for now. @Muhammad-Altabba open a new issue with respect to documentation, and I'll be here to jump and help out.
