### ISSUE TITLE
Does this sidetree implementation follows the sidetree project at decentralized-identity?

### ISSUE THREAD

**Issue by Muhammad-Altabba** [transmute-industries/sidetree.js#233]
Hello,
Does this repository follow the documentation and/or use the code at https://github.com/decentralized-identity/sidetree?

For example, looking at https://github.com/decentralized-identity/sidetree/blob/master/docs/core.md, there are some documented REST endpoints that I could not find in this repo.

Thanks in advance,

**Comment by OR13** [comment]
sorry for the late response, this code base is not up to date with the latest sidetree spec, but we are in the process of updating it.

**Comment by OR13** [comment]
This code base is now up to date, and we have confirmed conformance with ION, which is the only DID methods powered by the DIF reference implementation that we are aware of.

**Comment by OR13** [comment]
Closing this issue, but please feel free to raise more for any questions for find me in the DIF slack.
