### ISSUE TITLE
Should the DID document include verificationMethod?

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#273]
@OR13 Should the DID document include verificationMethod as specified in the DID Core ?

**Comment by OR13** [comment]
yes, it should.

**Comment by OR13** [comment]
@thomas-tran no, we have not released a v1 compatible version yet, upgrade is in progress.

**Comment by OR13** [comment]
We have now resolved this issue, see example: https://ropsten.element.transmute.industries/api/1.0/identifiers/did:elem:ropsten:EiCtwD11AV9e1oISQRHnMJsBC3OBdYDmx8xeKeASrKaw6A
