### ISSUE TITLE
Broken UI - Cant create wallet

### ISSUE THREAD

**Issue by downTheFallLine** [transmute-industries/sidetree.js#337]
1. Click wallet tab
2. click blue "Create wallet" button

nothing happens, other than error counter in lower right increments.  Console shows:

![image](https://user-images.githubusercontent.com/32492225/147288893-d9d8c5a0-f1b1-4b08-8eb6-55a3c3088bbf.png)

**Comment by OR13** [comment]
this was fixed at some point: demo is available here: https://ropsten.element.transmute.industries/ (this is the dashboard package in this repo).

**Comment by AlexYenkalov** [comment]
Hi @OR13 I get this issue when trying to run [the latest image of a dashboard](https://hub.docker.com/r/transmute/sidetree-dashboard) on Amazon EC2 Linux. Maybe you could advise where could be the problem.

AWS EC2 Linux has Node 16.3.0 and NPM 7.15.1 installed, along with the latest docker and docker-compose.

I've used the next command (the port was changed from 8080 to 8081 since 8080 is occupied by the IPFS node):
```
docker run -d --env-file=./.env.ropsten -p 8081:8081 transmute/sidetree-dashboard:latest
```

Here is the content of a config file that I've passed in

```
SIDETREE_METHOD='elem:ropsten'
DESCRIPTION="Sidetree on Ethereum Ledger and IPFS Cas"

# Sidetree Variables
MONGO_DB_CONNECTION_STRING="mongodb://localhost:27017/"
DATABASE_NAME="element-ropsten"
MAX_CONCURRENT_DOWNLOADS=20
BATCH_INTERVAL_IN_SECONDS=5
OBSERVING_INTERVAL_IN_SECONDS=5

# Element Node Variables
ELEMENT_CONTENT_ADDRESSABLE_STORE_SERVICE_URI='/ip4/127.0.0.1/tcp/5001'
ELEMENT_ANCHOR_CONTRACT="0x920b7DEeD5CdE055260cdDBD70C000Bbd5b30997"
ETHEREUM_RPC_URL='https://ropsten.infura.io/v3/920dbc65a097486aa871ff9a4ead3ead'
ETHEREUM_PROVIDER=$ETHEREUM_RPC_URL
ETHEREUM_MNEMONIC="wait dad copper crouch wheat slab fix crouch distance please damage slab"
ETHEREUM_PRIVATE_KEY="your private key here (will be ignored if ETHEREUM_MNEMONIC is provided)"
```

--

As the result, I'm getting the next error in the console when trying to create a wallet
```
universal-wallet.esm.js:894 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at universal-wallet.esm.js:894:36
    at h (universal-wallet.esm.js:126:40)
    at Generator._invoke (universal-wallet.esm.js:356:22)
    at Generator.next (universal-wallet.esm.js:181:21)
    at s (universal-wallet.esm.js:8:20)
    at a (universal-wallet.esm.js:30:9)
    at universal-wallet.esm.js:37:7
    at new Promise (<anonymous>)
    at universal-wallet.esm.js:26:12
    at universal-wallet.esm.js:909:17
```

**Comment by OR13** [comment]
hm, it seems like a problem with web crypto polyfill, maybe related to https://github.com/transmute-industries/universal-wallet/blob/d62e97d655928350fa9a506eb9b7eb142e4181b3/packages/universal-wallet/src/functions/seedToId.ts

try install

```
 "@peculiar/webcrypto": "^1.1.4",
 ```
 
 or bumping the version of   `universal-wallet`

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @AlexYenkalov)
