### ISSUE TITLE
README has explict styleguide

### ISSUE THREAD

**Issue by OR13** [transmute-industries/sidetree.js#70]
Maybe a section is needed... possible links:

https://basarat.gitbook.io/typescript/styleguide

Outside of the sidetree protocol, we should follow a conventional REST API style guide:

- https://restfulapi.net/
- https://google.github.io/styleguide/jsoncstyleguide.xml
- https://github.com/microsoft/api-guidelines

**Comment by BenjaminMoe** [comment]
It looks like this hasn't been commented on. We have linting, and enough code in the repository to have an implied style guide. And then we can make comments or edits as needed with pull requests. So we might re-open this later, but right now I'm going to close it due to lack of activity.
