### ISSUE TITLE
There are mongodb tests in core

### ISSUE THREAD

**Issue by gjgd** [transmute-industries/sidetree.js#90]
Need to separate the cas and db  packages in the same way that we did the ledger  package.
- split cas into cas  and cas-ipfs
- split db into db  and db-mongodb
- rename ethereum  into ledger-ethereum 

Then it will be possible to move MongoDbOperationStore to db-mongodb package and we won't have the cycle "@sidetree/cas -> @sidetree/db -> @sidetree/core -> @sidetree/cas"

**Comment by BenjaminMoe** [comment]
Following up on this. looks like `cas`, and `cas-ipfs` have been split. Looks like `ethereum` has been renamed to `ledger-ethereum`. So two out of three of these look done. For `db`, do we want or need to support more DB's than mongo?
